### PR TITLE
Feature/cache 06 errcachemiss

### LINKED ISSUE #82: CACHE-06 · Убрать redis.Nil из сервисного слоя
> **Скорее всего закроется сама.** Проверил PR #74 (CACHE-01): после переноса кеша в декоратор пакет `service` перестаёт импортировать `go-redis` вообще — задача решается побочным эффектом. Держим открытой до мержа #74, потом проверить и закрыть.
> 
> Но там же появляется новое: интерфейс `Cache` остаётся в `service/interfaces.go` и становится мёртвым — сервис его больше не принимает. Это надо убрать в том же PR.

---

### Зачем

`service/product_service.go` импортирует `github.com/redis/go-redis/v9` ради одного значения —
`redis.Nil`. Интерфейс `Cache` объявлен у потребителя правильно, но не объявил **свою**
ошибку промаха, поэтому потребитель тянет пакет реализации.

Зараза уже в моках: `mocks_test.go` тоже импортирует go-redis, чтобы вернуть `redis.Nil`.

Второй уровень кеша из #30 — in-memory LRU — будет обязан возвращать `redis.Nil` из памяти.
Это абсурд, и он приедет в код на следующей же задаче.

### Что сделать

- [x] Объявить `ErrCacheMiss` рядом с интерфейсом `Cache`.
- [x] Реализация Redis транслирует `redis.Nil` в неё.
- [x] Убрать импорт go-redis из `service` и из моков.

### Готово, когда

- [x] Пакет `service` не импортирует `go-redis`.
- [x] Мок кеша не знает про Redis вообще.

### На подумать — разобрать на ревью

- Правило «интерфейс у потребителя» касается только методов или ошибок тоже?
- Кто должен объявлять ошибку — тот, кто её возвращает, или тот, кто её проверяет?

---
**Оценка:** ~2 ч · **Блок 2** · **Зависит от:** блокирует #30

### PR DESCRIPTION
**Pull request by xdtqwd**

### CODE REVIEW

File: order-service/internal/service/interfaces.go [hunk 1]
```diff
@@ -2,10 +2,12 @@ package service
 
 import (
 	"context"
+	"errors"
 	"order-service/internal/domain"
-	"time"
 )
 
+var ErrCacheMiss = errors.New("cache miss")
```
Comment (kostyavelikiyi) [inline order-service/internal/service/interfaces.go]: `ErrCacheMiss` объявлен **дважды**:

```
cache/redis.go:12        var ErrCacheMiss = errors.New("cache miss")   ← возвращается
service/interfaces.go:9  var ErrCacheMiss = errors.New("cache miss")   ← не используется нигде
```

Одинаковый текст, разные значения. Тот, кто напишет `errors.Is(err, service.ErrCacheMiss)`, получит вечное `false` — кеш возвращает другую.

Это ровно `apperrors` заново, только на два дня моложе.

**Вопрос:** кто должен объявлять ошибку — тот, кто её возвращает, или тот, кто её проверяет? И как поймать такой дубль автоматически, раз компилятор молчит?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.**

Задача решена: `redis.Nil` транслируется в `ErrCacheMiss` внутри `cache`, пакет `service` больше не импортирует `go-redis`, мёртвый интерфейс `Cache` удалён. Именно это и просили.

Но заведена новая мина — прямо в этом PR, и она того же класса, что `apperrors`, который ты удаляешь соседним коммитом в #97.

---

**Про структуру.** Все восемь открытых PR ответвлены от `9243530` — это до мержа #73, который переписал `app.go` в фабрики. Поэтому все восемь конфликтуют, и конфликт везде один и тот же — `app.go`.

Хуже другое: `cached_product_repo.go` живёт в **трёх разных версиях**. В #92 — со счётчиком походов в БД, в #94–97 — с метриками, и эти ветки друг про друга не знают. Смержишь одну, потом другую — либо конфликт, либо, если разрешить невнимательно, чужая правка молча исчезнет.

Перед мержем стоит определиться с порядком и перебазировать, оставив в каждом PR только его дельту.

File: order-service/internal/service/interfaces.go (hunk 1 above)
Comment (kostyavelikiyi) [inline order-service/internal/service/interfaces.go]: Дубль на месте:

```
cache/redis.go:12        var ErrCacheMiss = errors.New("cache miss")   ← возвращается
service/interfaces.go:9  var ErrCacheMiss = errors.New("cache miss")   ← не используется
```

И новое, хуже: **ни одного `errors.Is` по любой из них во всём проекте**. Декоратор проверяет `err == nil`, поэтому таймаут или обрыв Redis молча трактуется как промах и уходит в БД.

**Вопрос:** если ошибку никто не проверяет — зачем она объявлена, тем более дважды? И как отличить «в кеше нет» от «Redis лежит»?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.**

Задача решена: `redis.Nil` транслируется в `ErrCacheMiss` внутри `cache`, `service` больше не импортирует `go-redis` — проверено `grep`-ом по всем веткам, включая моки. Мёртвый интерфейс `Cache` из `service/interfaces.go` убран. `cache.Get` переведён с `err == redis.Nil` на `errors.Is` — правильная форма.

Замечание с прошлой итерации не отработано — ветку не трогали с 29.08.

---

### Общее: ребейз теряет правки

За эту итерацию правки пропали **три раза**:

| Где | Что потерялось |
|---|---|
| `main` | подключение L1 к `app.go` — задача #30 закрыта, `NewL1ProductRepo` не вызывается ниоткуда |
| #94, #97 | все вызовы `metrics.*.Inc()` — пакет и `/metrics` есть, счётчики не инкрементятся |
| #94, #97 | роут `DELETE /products/{id}/cache` заменён строкой `/metrics` |

Плюс четыре коммита из пяти в #97 **не собираются** (`not enough arguments in call to repository.NewOrderRepo`) — зелёный только последний. `git bisect` по такой истории невозможен.

**Вопрос, который важнее любого замечания по коду:** как проверить, что ребейз ничего не потерял, кроме как читая диффы глазами? Подсказка — `git range-diff`.

File: order-service/internal/cache/redis.go [hunk 2]
```diff
@@ -3,40 +3,44 @@ package cache
...
+	"errors"
 	"time"
 
 	"github.com/redis/go-redis/v9"
 )
 
-func (c *RedisCache) Close() error {
-	return c.client.Close()
-}
+var ErrCacheMiss = errors.New("cache miss")
```
Comment (kostyavelikiyi) [inline order-service/internal/cache/redis.go:12]: Вот это правильно: ошибка объявлена там, где возвращается, и одна.

Проверь `grep`-ом, сколько объявлений `ErrCacheMiss` в #96 и #97 — они стоят на этой ветке, но твою правку не содержат.

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.**

Самая аккуратная работа из шести. Дубль `ErrCacheMiss` убран, `errors.Is` появился и в `cache`, и в декораторе, мёртвый интерфейс `Cache` из `service` удалён, `InvalidateCache` вычищен из сервиса и хендлера вместе с мёртвым комментарием — единственная ветка, где его нет.

**Но эта ветка откатывает #94:** здесь ноль вызовов `metrics.*.Inc()`, при живом пакете `metrics` и роуте `/metrics`. Счётчики будут вечными нулями.

Ещё: после `logger.Error("redis error")` код всё равно печатает `Debug("cache miss")` и идёт в БД. Fail-open — решение возможно правильное, но в логах ошибка и промах стали неразличимы.

Мутация: подменил `errors.Is(err, redis.Nil)` на заведомо ложное условие — тесты зелёные. Ни промах, ни ошибка не покрыты.

---

**Про стек.** #94 → #95 → #96 → #97: каждый следующий стоит на **доревьюшной** версии предыдущего. Мерж по порядку молча откатит правки — #95 отменит метрики из #94, #96 вернёт дубль `ErrCacheMiss`, который #95 убрал. Плюс все четыре несут старую копию CACHE-04, исправленную в #93.

И общее: `NewL1ProductRepo` не вызывается **ни в одной ветке и в `main`** — L1 мёртв с 30 августа, задача #30 при этом закрыта.

File: order-service/internal/repository/cached_product_repo.go [hunk 3]
```diff
@@ -36,12 +37,19 @@ func (r *CachedProductRepo) GetProductByID(ctx context.Context, id int) (*domain
...
-		r.logger.Info("cache hit", zap.String("key", key))
+	err := r.cache.Get(ctx, key, &p)
+	if err == nil {
+		r.logger.Debug("cache hit", zap.String("key", key))
+		metrics.CacheHits.WithLabelValues("l2").Inc()
 		return &p, nil
 	}
+	if !errors.Is(err, cache.ErrCacheMiss) {
+		r.logger.Error("redis error", zap.Error(err))
+		return nil, err
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go:48]: Проглатывание ошибки вылечено правильно — но теперь падение Redis превращает `GET /products/{id}` в 500. Раньше любая ошибка означала промах и поход в БД.

То есть кеш из ускорителя стал обязательной зависимостью. Задача этого не просила.

**Вопрос:** что правильнее для чтения товара — отдать 500 или сходить в БД и залогировать деградацию? И где должна жить эта политика: в декораторе или уровнем выше?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но одно решение надо принять осознанно.**

Задача #82 закрыта аккуратно и полнее, чем просили: `ErrCacheMiss` один, `service` не импортирует go-redis, мок про Redis не знает, мёртвый интерфейс `Cache` убран. Метрики #94 эта ветка больше не откатывает — все четыре `Inc()` на месте.

Но лечение поменяло контракт, и это стоит обсудить.

---

**Про очередь.** Открыто 20 PR, `main` не двигался с 30 августа. Это уже не вопрос удобства: каждый день ожидания — новый ребейз двадцати веток поверх меняющегося кода, а ребейз у тебя уже терял правки. Проблема сама себя воспроизводит.

Предлагаю выбрать несколько PR, довести их до конца и влить, а остальные перебазировать поверх — вместо того чтобы держать всё в воздухе.
