### PR TITLE
Refactor/clean 01 dead code

### LINKED ISSUE #81: CLEAN-01 · Мёртвый пакет apperrors и типы-дубли
### Зачем

`internal/apperrors` не импортируется **ниоткуда**, но объявляет `ErrInsufficientStock`
и `ErrOrderAlreadyCancelled` — дословные копии того, что лежит в `domain/errors.go`.

Это не лишний файл, а заряженная мина: тот, кто напишет
`errors.Is(err, apperrors.ErrInsufficientStock)`, получит вечное `false`, потому что
репозиторий возвращает доменную ошибку. Компилятор промолчит, тесты пройдут.

Туда же три мёртвых типа — `repository.Order`, `repository.OrderItem`, `repository.Product`,
побайтовые копии доменных, не используемые нигде.

Линтер их не показывает: `unused` не трогает экспортированные идентификаторы. Та же слепота,
из-за которой в PR #75 прошёл неподключённый L1.

### Что сделать

- [x] Удалить пакет `apperrors` целиком.
- [x] Удалить мёртвые структуры из `repository/order.go` и `repository/product.go`.
- [x] Убрать мёртвый комментарий `// убедимся что service импортируется` в `handler.go`.
- [x] Проверить, что сборка и тесты зелёные — если что-то отвалилось, значит код был не мёртвый.

### Готово, когда

- [x] Пакета `apperrors` нет, доменные ошибки живут в одном месте.
- [x] `grep` по проекту не находит `repository.Order`, `repository.OrderItem`, `repository.Product`.

### На подумать — разобрать на ревью

- Раз `unused` не ловит экспортированные типы — чем ещё можно находить мёртвый код в Go?
- Почему дубль sentinel-ошибки опаснее дубля обычной функции?

---
**Оценка:** ~2 ч · **Блок 1**

### PR DESCRIPTION
**Pull request by xdtqwd**

### CODE REVIEW

File: order-service/internal/repository/product.go [hunk 1]
```diff
@@ -52,3 +45,7 @@ func (r *ProductRepo) GetProductByID(ctx context.Context, id int) (*domain.Produ
 	}
 	return &p, nil
 }
+
+func (r *ProductRepo) InvalidateByID(ctx context.Context, id int) error {
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/product.go:49]: Этот no-op не удалён, а **переехал** сюда из `product_repo.go`. Возвращает `nil`, не делая ничего.

Задача была про мёртвый код — а метод, который существует только чтобы удовлетворить интерфейс и врёт вызывающему, это он и есть.

**Вопрос:** он появился в #93, чтобы `ProductRepo` подошёл под `ProductStorage`. Что правильнее — оставить заглушку или убрать метод из интерфейса?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо доделать.**

Главное сделано и проверено: пакет `apperrors` удалён целиком, три типа-дубля (`repository.Order`, `OrderItem`, `Product`) удалены, ссылок не осталось, сборка и `vet` чистые.

Два пункта из чеклиста задачи #81 не закрыты — отметил в коде и ниже.

**Мёртвый комментарий `// убедимся что service импортируется` в `handler.go:176` остался.** Он был отдельным пунктом задачи. Строка не в диффе этого PR, поэтому пишу здесь.

И общее по ветке: `gofmt -l` даёт **пять** файлов — `app.go`, `handler/errors.go`, `cached_product_repo.go`, `product_repo.go`, `mocks_test.go`. Линтер это не ловит, потому что секция `formatters` потерялась при миграции на v2 (задача #88).

---

**Про структуру.** Все восемь открытых PR ответвлены от `9243530` — это до мержа #73, который переписал `app.go` в фабрики. Поэтому все восемь конфликтуют, и конфликт везде один и тот же — `app.go`.

Хуже другое: `cached_product_repo.go` живёт в **трёх разных версиях**. В #92 — со счётчиком походов в БД, в #94–97 — с метриками, и эти ветки друг про друга не знают. Смержишь одну, потом другую — либо конфликт, либо, если разрешить невнимательно, чужая правка молча исчезнет.

Перед мержем стоит определиться с порядком и перебазировать, оставив в каждом PR только его дельту.

File: order-service/internal/repository/product.go (hunk 1 above)
Comment (kostyavelikiyi) [inline order-service/internal/repository/product.go:49]: Этот no-op не удалён, а **переехал** сюда из `product_repo.go`. Возвращает `nil`, не делая ничего.

Задача была про мёртвый код — а метод, существующий только чтобы удовлетворить интерфейс и врущий вызывающему, это он и есть.

**Вопрос:** в #93 ты убрал `InvalidateByID` из `ProductStorage` целиком — правильное решение. Почему здесь оно не применено?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.**

Главное по задаче сделано и проверено: пакет `apperrors` удалён целиком, три типа-дубля (`repository.Order`, `OrderItem`, `Product`) удалены, `grep` чист. Это хорошо.

Но блокирует другое.

**Четыре коммита из пяти не собираются:**

```
8020dc6 FAIL  feat: CACHE-05 Prometheus metrics
165f66a FAIL  feat: CACHE-06 ErrCacheMiss
45d7b87 FAIL  refactor: ARCH-07 Querier
1fea83e FAIL  refactor: CLEAN-01 remove apperrors
63092bc OK    fix: pass invalidator to NewOrderRepo
```

`not enough arguments in call to repository.NewOrderRepo`. Зелёный только последний. `git bisect` по такой истории невозможен — а это ровно то, ради чего заведена задача #69.

**И метрики здесь тоже мёртвые** — `.Inc()` не вызывается ни разу, как и в #94. Подробнее написал там.

**Два пункта чеклиста не закрыты:** мёртвый комментарий `// убедимся что service импортируется` в `handler.go:176` на месте (строка не в диффе, поэтому пишу здесь), и `gofmt -l` даёт четыре файла. Последнее не твоя вина — в `.golangci.yml` нет секции `formatters`, это задача #88. А вот `.golangci.bck.yml` рядом — сам по себе мёртвый файл в PR про мёртвый код.

---

### Общее: ребейз теряет правки

За эту итерацию правки пропали **три раза**:

| Где | Что потерялось |
|---|---|
| `main` | подключение L1 к `app.go` — задача #30 закрыта, `NewL1ProductRepo` не вызывается ниоткуда |
| #94, #97 | все вызовы `metrics.*.Inc()` — пакет и `/metrics` есть, счётчики не инкрементятся |
| #94, #97 | роут `DELETE /products/{id}/cache` заменён строкой `/metrics` |

Плюс четыре коммита из пяти в #97 **не собираются** (`not enough arguments in call to repository.NewOrderRepo`) — зелёный только последний. `git bisect` по такой истории невозможен.

**Вопрос, который важнее любого замечания по коду:** как проверить, что ребейз ничего не потерял, кроме как читая диффы глазами? Подсказка — `git range-diff`.

File: order-service/internal/service/interfaces.go [hunk 2]
```diff
@@ -2,24 +2,21 @@ package service
 
 import (
 	"context"
+	"errors"
 	"order-service/internal/domain"
-	"time"
 )
 
+var ErrCacheMiss = errors.New("cache miss")
```
Comment (kostyavelikiyi) [inline order-service/internal/service/interfaces.go]: PR про удаление дублей sentinel-ошибок **сам содержит дубль sentinel-ошибки**.

`ErrCacheMiss` объявлена здесь и в `cache/redis.go:12`. Эта копия не используется никем, `errors.Is` по ней нет нигде.

Это буквально мина из текста задачи #81, которую ты цитируешь в описании: «`errors.Is` даст вечный `false`, компилятор промолчит». Только в новом месте.

**Вопрос:** #95 стоит ниже по стеку и эту копию уже убрал. Почему её здесь снова две?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.**

По задаче сделано: `apperrors` удалён, три типа-дубля удалены, `grep` чист, дублирующий `Invalidator` сведён в `querier.go`. `ProductRepo.InvalidateByID` наконец удалён.

Блокирует другое.

**Четыре коммита из шести не собираются** (`app.go:34`, `not enough arguments in call to NewOrderRepo`). Было четыре из пяти — стало четыре из шести. `git bisect` по такой истории невозможен, это #69.

**Мёртвый комментарий `// убедимся что service импортируется` в `handler.go:176` на месте** — отдельный пункт чеклиста, галочка отмечена. Третье ревью подряд.

`gofmt -l` даёт `repository/product_repo.go` (две пустые строки после `package`) и `app.go`. И ветка откатывает метрики #94.

---

**Про стек.** #94 → #95 → #96 → #97: каждый следующий стоит на **доревьюшной** версии предыдущего. Мерж по порядку молча откатит правки — #95 отменит метрики из #94, #96 вернёт дубль `ErrCacheMiss`, который #95 убрал. Плюс все четыре несут старую копию CACHE-04, исправленную в #93.

И общее: `NewL1ProductRepo` не вызывается **ни в одной ветке и в `main`** — L1 мёртв с 30 августа, задача #30 при этом закрыта.

File: order-service/internal/repository/product.go (hunk 1 above)
Comment (kostyavelikiyi) [inline order-service/internal/repository/product.go:49]: PR про удаление мёртвого кода этот метод **перенёс**, а не удалил — он приехал сюда из `product_repo.go`.

По-прежнему возвращает `nil`, никем не вызывается, никакому интерфейсу не нужен.

**Вопрос:** в #93 ты убрал `InvalidateByID` из `ProductStorage` целиком — правильное решение. Почему здесь оно не применено?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но после #96.**

Тело задачи #81 сделано: `apperrors` удалён, `repository.Order`/`OrderItem`/`Product` удалены, `grep` чист. Мёртвый комментарий убран, дубль `ErrCacheMiss` устранён. Оба собственных коммита собираются — дисциплина выросла.

Но ветка целиком тянет три несобирающихся коммита из #94 и #95.

И head назван `fix: gofmt product_repo.go and app.go`, а `gofmt -l` показывает `handler/handler.go` и `service/interfaces.go` — ровно те два файла, форматирование которых сломала эта же цепочка коммитом `02a2a49`. Отформатированы файлы, которые никто не ломал.

Отдельно: `.golangci.bck.yml` всё ещё в репозитории, и в нём — в отличие от рабочего конфига — включён `gofmt`. Поэтому CI формат не ловит, а файл с правильной настройкой лежит рядом мёртвым грузом. Задача #81 ровно про такие файлы.

---

**Про очередь.** Открыто 20 PR, `main` не двигался с 30 августа. Это уже не вопрос удобства: каждый день ожидания — новый ребейз двадцати веток поверх меняющегося кода, а ребейз у тебя уже терял правки. Проблема сама себя воспроизводит.

Предлагаю выбрать несколько PR, довести их до конца и влить, а остальные перебазировать поверх — вместо того чтобы держать всё в воздухе.
