### PR TITLE
Feature/cache 05 metrics

### LINKED ISSUE #33: CACHE-05 · Метрики попаданий в кеш
### Зачем

Сейчас про кеш можно узнать только из `logger.Info("cache hit:")`
(`product_service.go:34`) — а это ещё и лишняя строка в логе на каждый запрос под нагрузкой.

### Что сделать

- [x] Счётчики `cache_hits_total` / `cache_misses_total` с лейблом уровня (`l1` / `l2`).
- [x] Логи на каждое попадание снизить до `Debug`.

### Готово, когда

- [x] Hit rate виден на графике и растёт до правдоподобных значений под нагрузкой k6.

---
**Оценка:** ~3 ч · **Блок 2** · **Зависит от:** #55 · **Зависит от:** #30

### PR DESCRIPTION
**Pull request by xdtqwd**

### CODE REVIEW

File: order-service/internal/metrics/metrics.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+	CacheMisses = prometheus.NewCounterVec(
+		prometheus.CounterOpts{
+			Name: "cache_misses_total",
+			Help: "Total cache misses by level",
+		},
+		[]string{"level"},
+	)
+)
+
+func init() {
```
Comment (kostyavelikiyi) [inline order-service/internal/metrics/metrics.go:22]: `MustRegister` в `init()` — регистрация в глобальный реестр при импорте пакета. Работает, но два инстанса в одном процессе уже не создать: вторая регистрация паникует.

**Вопрос:** как это скажется на тестах, если завтра захочется проверить, что счётчик действительно растёт?

File: order-service/internal/repository/cached_product_repo.go [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+	return r.repo.GetProducts(ctx)
+}
+
+func (r *CachedProductRepo) GetProductByID(ctx context.Context, id int) (*domain.Product, error) {
+	key := fmt.Sprintf("product:%d", id)
+
+	var p domain.Product
+	if err := r.cache.Get(ctx, key, &p); err == nil {
+		r.logger.Debug("cache hit", zap.String("key", key))
+	metrics.CacheHits.WithLabelValues("l2").Inc()
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go]: Строка не выровнена — `gofmt` бы это поймал, но секция `formatters` потерялась при переходе линтера на v2 (задача #88). Сейчас `gofmt -l` по ветке даёт **пять** файлов.

И по лейблам: задача просила `l1`/`l2`, здесь только `l2`. Для этой ветки честно — L1 живёт в #75. Но после мержа обоих про второй уровень нужно не забыть.

**Review by kostyavelikiyi — COMMENTED** [review]
**Ок, можно мержить.** Лучший из восьми.

Метрики зарегистрированы, `/metrics` через `promhttp` подключён, счётчики инкрементятся, кеш в сборке. Логи `cache hit`/`cache miss` снижены до `Debug` — ровно то, что просила задача, и этот пункт часто забывают.

Два замечания в коде, оба мелкие.

Отдельно: задача #33 была помечена как зависящая от #55, где `/metrics` и Prometheus. Ты сделал эндпоинт сам — это нормально, но стоит отметить в #55, что часть уже закрыта, иначе там будет дубль.

---

**Про структуру.** Все восемь открытых PR ответвлены от `9243530` — это до мержа #73, который переписал `app.go` в фабрики. Поэтому все восемь конфликтуют, и конфликт везде один и тот же — `app.go`.

Хуже другое: `cached_product_repo.go` живёт в **трёх разных версиях**. В #92 — со счётчиком походов в БД, в #94–97 — с метриками, и эти ветки друг про друга не знают. Смержишь одну, потом другую — либо конфликт, либо, если разрешить невнимательно, чужая правка молча исчезнет.

Перед мержем стоит определиться с порядком и перебазировать, оставив в каждом PR только его дельту.

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.** Понижаю с прошлого «можно мержить» — ребейз выкинул инструментацию.

Проверил `grep`-ом по веткам:

```
#94  вызовов metrics.*.Inc():  0
#95  вызовов metrics.*.Inc():  1
#96  вызовов metrics.*.Inc():  1
#97  вызовов metrics.*.Inc():  0
```

Пакет `metrics` создан, `init()` регистрирует счётчики, `/metrics` отдаётся — а `.Inc()` не вызывается **нигде**. `CounterVec` без единого `WithLabelValues` не выдаёт ни одной серии: на `/metrics` не будет даже нулей. Хит-рейт на графике не появится.

Там же логи `cache hit`/`cache miss` откатились с `Debug` обратно на `Info` — то есть прошлая правка тоже потерялась.

Отдельно: коммит `fix: gofmt formatting` меняет **только бинарный `order-service/.DS_Store`**, ни одного `.go`. `gofmt -l` по-прежнему даёт файлы. Кстати, `.DS_Store` вообще не должен быть в индексе — он есть в `.gitignore`, но был добавлен раньше игнора (это задача #90).

**Проверь сам:** запусти сервис, открой `/metrics` и найди там `cache_hits_total`.

---

### Общее: ребейз теряет правки

За эту итерацию правки пропали **три раза**:

| Где | Что потерялось |
|---|---|
| `main` | подключение L1 к `app.go` — задача #30 закрыта, `NewL1ProductRepo` не вызывается ниоткуда |
| #94, #97 | все вызовы `metrics.*.Inc()` — пакет и `/metrics` есть, счётчики не инкрементятся |
| #94, #97 | роут `DELETE /products/{id}/cache` заменён строкой `/metrics` |

Плюс четыре коммита из пяти в #97 **не собираются** (`not enough arguments in call to repository.NewOrderRepo`) — зелёный только последний. `git bisect` по такой истории невозможен.

**Вопрос, который важнее любого замечания по коду:** как проверить, что ребейз ничего не потерял, кроме как читая диффы глазами? Подсказка — `git range-diff`.

File: order-service/internal/metrics/metrics.go (hunk 1 above)
Comment (kostyavelikiyi) [inline order-service/internal/metrics/metrics.go:22]: `MustRegister` в `init()` — регистрация в глобальный реестр при импорте пакета. Замечание с прошлой итерации, не отработано.

**Вопрос:** как это скажется на тесте, который захочет проверить, что счётчик реально растёт? Вторая регистрация паникует.

File: order-service/internal/app/app.go [hunk 3]
```diff
@@ -58,7 +59,7 @@ func setupRoutes(h *handler.Handler) http.Handler {
 	r.HandleFunc("/orders", h.GetOrders).Methods("GET")
 	r.HandleFunc("/orders/{id}", h.GetOrderByID).Methods("GET")
 	r.HandleFunc("/orders/{id}/cancel", h.CancelOrder).Methods("POST")
-	r.HandleFunc("/products/{id}/cache", h.InvalidateProductCache).Methods("DELETE")
+	r.Handle("/metrics", promhttp.Handler())
```
Comment (kostyavelikiyi) [inline order-service/internal/app/app.go:64]: Эта строка **заменила** роут `DELETE /products/{id}/cache`, а не добавилась к нему.

При этом `Handler.InvalidateProductCache`, `ProductService.InvalidateCache` и метод в интерфейсе остались — теперь недостижимый экспортированный код, который `unused` не ловит.

Забавно, что снять эту ручку просила задача #32 — но не так и не здесь.

**Вопрос:** это осознанное решение или потеря при ребейзе?

File: order-service/internal/metrics/metrics.go (hunk 1 above)
Comment (xdtqwd) [reply order-service/internal/metrics/metrics.go:22]: При втором импорте пакета metrics — паника. В тестах это значит нельзя запустить два теста которые импортируют этот пакет в разных goroutine или пересоздать реестр. Решение — принимать *prometheus.Registry как зависимость и регистрировать туда.

File: order-service/internal/app/app.go (hunk 3 above)
Comment (xdtqwd) [reply order-service/internal/app/app.go:64]: Потеря при ребейзе — X ours взял нашу версию setupRoutes без /cache эндпоинта, и строка с /metrics встала на его место вместо того чтобы добавиться.

File: order-service/internal/repository/cached_product_repo.go [hunk 4]
```diff
@@ -37,11 +38,13 @@ func (r *CachedProductRepo) GetProductByID(ctx context.Context, id int) (*domain
 
 	var p domain.Product
 	if err := r.cache.Get(ctx, key, &p); err == nil {
-		r.logger.Info("cache hit", zap.String("key", key))
+		r.logger.Debug("cache hit", zap.String("key", key))
+	metrics.CacheHits.WithLabelValues("l2").Inc()
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go]: Здесь метрика вернулась — хорошо. Но строкой выше любая ошибка Redis инкрементит `cache_misses_total`: таймаут считается промахом.

Под сетевыми проблемами hit rate будет врать в сторону промахов — то есть метрика, которую ты добавляешь, покажет неверную картину именно тогда, когда она нужнее всего.

Это чинится в #95 (`errors.Is(err, cache.ErrCacheMiss)`), но #95 при этом откатывает твои метрики. **Вопрос:** как две правки, нужные обе, оказались взаимоисключающими?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.**

Метрики вернулись — два вызова `.Inc()` на месте, логи снова `Debug`, роут `DELETE /products/{id}/cache` восстановлен рядом с `/metrics`. Прошлые блокеры закрыты.

Но коммит `fix: gofmt formatting` по-прежнему не форматирует: `gofmt -l` ругается на `internal/app/app.go` и `internal/repository/cached_product_repo.go` — **оба файла из последнего коммита**. В прошлый раз тот коммит менял только `.DS_Store`; сейчас он менял `.go`, но результат тот же.

Отдельно: лейбл `level` только `"l2"`. `cache_hits_total{level="l1"}` не появится никогда — в `l1_product_repo.go` вызовов метрик нет, да и L1 не в сборке. Галочка «счётчики с лейблом уровня (l1/l2)» выполнена наполовину.

**Вопрос:** какими действиями получить `l1` на графике? Их два, и оба не в этом PR.

---

**Про стек.** #94 → #95 → #96 → #97: каждый следующий стоит на **доревьюшной** версии предыдущего. Мерж по порядку молча откатит правки — #95 отменит метрики из #94, #96 вернёт дубль `ErrCacheMiss`, который #95 убрал. Плюс все четыре несут старую копию CACHE-04, исправленную в #93.

И общее: `NewL1ProductRepo` не вызывается **ни в одной ветке и в `main`** — L1 мёртв с 30 августа, задача #30 при этом закрыта.

File: load-tests/results/cache03_after_singleflight.md [hunk 5]
```diff
@@ -0,0 +1,15 @@
+# CACHE-03 — с singleflight
```
Comment (kostyavelikiyi) [inline load-tests/results/cache03_after_singleflight.md:1]: Эти три файла — про CACHE-03, а не про метрики. И `singleflight` в коде этой ветки нет.

Цифры внутри — «TTL 5s», «DB запросов: 1» — те самые, от которых ты отказался в #92, где написал, что TTL пять минут и замер невозможен.

**Вопрос:** как отчёт о чужой фиче попал в этот PR? И какой из двух текстов правда?

File: order-service/internal/app/app.go [hunk 6]
```diff
@@ -30,7 +31,8 @@ type App struct {
 func newRepositories(pool *pgxpool.Pool, c *cache.RedisCache, logger *zap.Logger) (*repository.OrderRepo, repository.ProductStorage) {
 	productRepo := repository.NewProductRepo(pool)
 	cachedProductRepo := repository.NewCachedProductRepo(productRepo, c, logger)
-	return repository.NewOrderRepo(pool), cachedProductRepo
+	l1ProductRepo := repository.NewL1ProductRepo(cachedProductRepo)
+	return repository.NewOrderRepo(pool, cachedProductRepo), l1ProductRepo
```
Comment (kostyavelikiyi) [inline order-service/internal/app/app.go:35]: Сюда передаётся `cachedProductRepo` — это L2. А на чтение выше отдаётся `l1ProductRepo`.

Значит после заказа сбрасывается второй уровень, а первый продолжает отдавать старый остаток до истечения своего TTL. Воспроизведено: до 10 секунд.

**Вопрос:** какой слой должен получать инвалидацию, если стек трёхуровневый?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.** Прошлые замечания закрыты, но появилось хуже.

Закрыто: `gofmt` теперь чистый по своим файлам, лейблы `l1` и `l2` оба есть и разложены по правильным слоям, L1 подключён в `app.go`.

**Первое.** Коммит CACHE-05 добавляет три файла с результатами **CACHE-03**: `cache03_before_singleflight.md`, `cache03_after_singleflight.md`, `cache03_with_singleflight.md`. В них «TTL: 5s» и «DB запросов при stampede: 1». При этом `grep singleflight` по коду этой ветки даёт **пусто** — фичи здесь нет.

А в #92 ты сам написал, что TTL захардкожен на 5 минут и замер невозможен. То есть PR про метрики несёт в `main` отчёт о фиче, которой в нём нет, с цифрами, от которых ты отказался в соседней ветке.

**Второе.** L1 подключён, но инвалидируется L2: `app.go` отдаёт `l1ProductRepo` на чтение, а инвалидатором в `NewOrderRepo` передаёт `cachedProductRepo`. Воспроизведено тестом: после списания остатка `GET` до десяти секунд отдаёт старый `stock`.

**Третье.** Ветка возвращает роут `DELETE /products/{id}/cache`, который #93 удаляет по критерию задачи #32. Встанет после #93 — эндпоинт вернётся.

Плюс: два коммита из семи не собираются; мутация — вырезал все четыре `metrics.*.Inc()`, тесты зелёные; галочка «hit rate виден на графике» отмечена, а Prometheus и Grafana в `docker-compose` нет.

---

**Про очередь.** Открыто 20 PR, `main` не двигался с 30 августа. Это уже не вопрос удобства: каждый день ожидания — новый ребейз двадцати веток поверх меняющегося кода, а ребейз у тебя уже терял правки. Проблема сама себя воспроизводит.

Предлагаю выбрать несколько PR, довести их до конца и влить, а остальные перебазировать поверх — вместо того чтобы держать всё в воздухе.

**Comment by kostyavelikiyi** [comment]
Закрываю: содержимое в main через #97.

Коммиты CACHE-05 (`a18b0ff`…`336a2db`) входили в общую базу с #95–#97 и уехали вместе с ними. Единственный твой коммит сверху — `387dcf7`, который передаёт `l1ProductRepo` инвалидатором вместо `cachedProductRepo`.

Он важный, и я его забрал отдельно. Без него сброс чистил Redis, но не L1 в памяти: заказ уменьшает остаток, L2 сброшен, а следующие 10 секунд отдаётся старый остаток из L1. Ты это увидел сам — хорошо.
