### PR TITLE
Refactor/arch 07 querier

### LINKED ISSUE #80: ARCH-07 · Ввести Querier — до транзакционного менеджера
### Зачем

Все семь методов репозиториев ходят в `r.pool` напрямую. Подменить пул на `pgx.Tx` нечем:
нет ни общей абстракции, ни передачи транзакции через контекст.

Задачи #46 (транзакция через два репозитория) и #49 (outbox в той же транзакции) потребуют
переписать сигнатуры всех методов, оба конструктора, оба интерфейса и всю сборку в `app.go`.
Введённый заранее `Querier` превращает это в правку одной строки на метод.

Заодно вскроется, что разрез на `OrderRepo`/`ProductRepo` фиктивен: внутри своей транзакции
`OrderRepo` и читает, и пишет таблицу `products` — то есть ходит в чужую вотчину в обход
второго репозитория.

### Что сделать

- [x] Объявить интерфейс `Querier` с методами `Query`, `QueryRow`, `Exec`.
- [x] Проверить, что `*pgxpool.Pool` и `pgx.Tx` оба ему удовлетворяют — это так и есть, но убедиться самому.
- [x] Перевести все методы репозиториев на `Querier` вместо `*pgxpool.Pool`.
- [x] Решить, откуда метод берёт `Querier`: поле, аргумент или контекст.

### Готово, когда

- [x] Любой метод репозитория работает и с пулом, и с транзакцией без изменения кода.
- [x] Тесты и сборка зелёные, поведение не изменилось.

### На подумать — разобрать на ревью

- Три способа протащить транзакцию — поле структуры, явный аргумент, контекст. У каждого своя цена, назови её.
- Почему `OrderRepo` вообще пишет в `products`? Это ошибка разреза или неизбежность транзакции?

---
**Оценка:** ~1 день · **Блок 1** · **Зависит от:** блокирует #46, #49

### PR DESCRIPTION
**Pull request by xdtqwd**

### CODE REVIEW

File: order-service/internal/repository/order_repo.go [hunk 1]
```diff
@@ -3,9 +3,11 @@ package repository
 import "github.com/jackc/pgx/v5/pgxpool"
 
 type OrderRepo struct {
-	pool *pgxpool.Pool
+	pool        *pgxpool.Pool
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order_repo.go]: Структура держит **и** `pool`, **и** `db Querier`, причём конструктор кладёт в оба одно и то же: `{pool: pool, db: pool}`.

Поле `db` при этом в `CreateOrder` не используется — там работа идёт через `tx` из `Begin`. То есть абстракция введена, а самый важный метод её обошёл.

**Вопрос:** проверь `grep`-ом, в скольких методах `OrderRepo` реально используется `r.db`.

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но цель достигнута наполовину.**

`Querier` объявлен верно. Проверил компиляцией: `pgx.Tx` ему удовлетворяет, `ProductRepo` принимает транзакцию — это работает.

Но `OrderRepo` — нет:

```
cannot use tx (variable of interface type pgx.Tx) as *pgxpool.Pool value
in argument to NewOrderRepo
```

И в `CreateOrder` (`order.go:29`) осталось `tx, err := r.pool.Begin(ctx)`, после чего метод работает с `tx` напрямую — `Querier` там не участвует вообще.

Задача затевалась ради #46 (транзакция через два репозитория) и #49 (outbox в той же транзакции). В обеих транзакция должна приходить **снаружи**. Сейчас она по-прежнему рождается внутри `CreateOrder` и наружу не выходит — то есть главный блокер не снят.

**Вопрос:** `Begin` не входит в `Querier` и не может — у `pgx.Tx` его нет. Значит нужен второй, отдельный интерфейс. Какой у него метод и кто его реализует?

---

**Про структуру.** Все восемь открытых PR ответвлены от `9243530` — это до мержа #73, который переписал `app.go` в фабрики. Поэтому все восемь конфликтуют, и конфликт везде один и тот же — `app.go`.

Хуже другое: `cached_product_repo.go` живёт в **трёх разных версиях**. В #92 — со счётчиком походов в БД, в #94–97 — с метриками, и эти ветки друг про друга не знают. Смержишь одну, потом другую — либо конфликт, либо, если разрешить невнимательно, чужая правка молча исчезнет.

Перед мержем стоит определиться с порядком и перебазировать, оставив в каждом PR только его дельту.

File: order-service/internal/repository/order_repo.go (hunk 1 above)
Comment (kostyavelikiyi) [inline order-service/internal/repository/order_repo.go]: Структура держит **и** `pool`, **и** `db Querier`, конструктор кладёт в оба одно и то же.

Поле `db` в `CreateOrder` не используется — там работа идёт через `tx` из `Begin`. Абстракция введена, а главный метод её обошёл.

**Вопрос:** `Begin` в `Querier` не входит и не может — у `pgx.Tx` его нет. Значит нужен второй интерфейс. Какой у него метод и кто его реализует?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но цель достигнута наполовину.** Ветку не трогали с 29.08.

Проверил компиляцией в worktree:

```go
var _ Querier = (*pgxpool.Pool)(nil)   // ок
var _ Querier = (pgx.Tx)(nil)          // ок
_ = NewProductRepo(tx)                 // ок
_ = NewOrderRepo(tx, nil)              // ОШИБКА
```

`cannot use tx (variable of interface type pgx.Tx) as *pgxpool.Pool value`.

`Querier` объявлен корректно и минимально, `pgx.Tx` ему удовлетворяет без адаптеров, `ProductRepo` честно переведён — это половина сделана правильно.

Но критерий задачи «любой метод репозитория работает и с пулом, и с транзакцией» отмечен галочкой и не выполнен. И задача затевалась ради #46 и #49 — там транзакция должна приходить **снаружи**, а `CreateOrder` по-прежнему делает `r.pool.Begin` сам.

**Вопрос:** как в эту транзакцию встроится outbox из #49, который должен писать в неё из другого репозитория?

---

### Общее: ребейз теряет правки

За эту итерацию правки пропали **три раза**:

| Где | Что потерялось |
|---|---|
| `main` | подключение L1 к `app.go` — задача #30 закрыта, `NewL1ProductRepo` не вызывается ниоткуда |
| #94, #97 | все вызовы `metrics.*.Inc()` — пакет и `/metrics` есть, счётчики не инкрементятся |
| #94, #97 | роут `DELETE /products/{id}/cache` заменён строкой `/metrics` |

Плюс четыре коммита из пяти в #97 **не собираются** (`not enough arguments in call to repository.NewOrderRepo`) — зелёный только последний. `git bisect` по такой истории невозможен.

**Вопрос, который важнее любого замечания по коду:** как проверить, что ребейз ничего не потерял, кроме как читая диффы глазами? Подсказка — `git range-diff`.

File: order-service/internal/repository/order_repo.go [hunk 2]
```diff
@@ -1,11 +1,26 @@
...
 
-import "github.com/jackc/pgx/v5/pgxpool"
+import (
+	"context"
+
+	"github.com/jackc/pgx/v5"
+	"github.com/jackc/pgx/v5/pgxpool"
+)
+
+type Beginner interface {
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order_repo.go:9]: `grep` по всему проекту даёт **одно** вхождение — само это объявление. Интерфейс написан и не используется.

Шестой случай подряд: DTO в ARCH-03, L1 дважды, декоратор в CACHE-03, метрики, теперь `Beginner`.

**Вопрос:** ты объявил ровно то, чего не хватало — метод для старта транзакции. Что помешало довести до конца: подставить его в `OrderRepo` вместо `pool`?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.**

`Querier` объявлен минимально и точно, `ProductRepo` переведён полностью — половина задачи сделана честно. Но по сути замечания ничего не изменилось: `NewOrderRepo` по-прежнему требует `*pgxpool.Pool`, `CreateOrder` делает `r.pool.Begin` сам, поле `db Querier` используется только на чтение. Подать в `OrderRepo` транзакцию нельзя.

Коммит `0534c36` чинит сборку после ребейза — к сути отношения не имеет.

Плюс ветка откатывает соседей: `ErrCacheMiss` снова в двух местах (#95 это убрал), ноль вызовов `metrics.*.Inc()` (#94 это вернул). Пять коммитов из шести не собираются.

**Вопрос:** как в транзакцию из `CreateOrder` встроится outbox из #49, если она рождается внутри метода и наружу не выходит?

---

**Про стек.** #94 → #95 → #96 → #97: каждый следующий стоит на **доревьюшной** версии предыдущего. Мерж по порядку молча откатит правки — #95 отменит метрики из #94, #96 вернёт дубль `ErrCacheMiss`, который #95 убрал. Плюс все четыре несут старую копию CACHE-04, исправленную в #93.

И общее: `NewL1ProductRepo` не вызывается **ни в одной ветке и в `main`** — L1 мёртв с 30 августа, задача #30 при этом закрыта.

File: order-service/internal/repository/order_repo.go [hunk 3]
```diff
@@ -1,11 +1,25 @@
...
-	pool *pgxpool.Pool
+	pool        Beginner
+	db          Querier
+	invalidator Invalidator
 }
 
-func NewOrderRepo(pool *pgxpool.Pool) *OrderRepo {
-	return &OrderRepo{pool: pool}
+func NewOrderRepo(pool Beginner, invalidator Invalidator) *OrderRepo {
+	return &OrderRepo{pool: pool, db: pool.(Querier), invalidator: invalidator}
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order_repo.go:24]: Вот здесь и обход. Тип в сигнатуре расширили до `Beginner`, а связь с `Querier` вернули непроверяемым приведением.

Итог: ошибка компиляции превратилась в панику при старте, компилятор молчит. Прогнал — паника есть: `interface conversion: fakeBeginner is not Querier: missing method Exec`.

`pgx.Tx` проходит не потому, что абстракция построена верно, а потому что у него есть `Begin` для вложенных транзакций.

**Вопрос:** задача просила выбрать один из трёх способов протащить `Querier` — поле, аргумент или контекст — и назвать цену. Почему выбран четвёртый: приведение типа?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.** Формальный критерий достигнут, но способом, против которого задача и заводилась.

Проверил компиляцией, три прогона:

```
NewOrderRepo(tx, nil)      где tx это pgx.Tx     → компилируется
NewOrderRepo(q, nil)       где q это Querier      → НЕ компилируется
NewOrderRepo(fakeBeginner) без Exec               → ПАНИКА в конструкторе
```

Подробности в комментарии к коду.

И второе: критерий «любой метод работает и с пулом, и с транзакцией» для `CreateOrder` не выполнен — метод сам зовёт `Begin`. Передашь ему `pgx.Tx` — получишь SAVEPOINT, «коммит» которого не коммит, а инвалидация кеша отработает до реального внешнего коммита. Именно этого #46 и #49 получить не должны.

Плюс ветка несёт худшую копию логики из #93: `_ = err // best-effort` вместо лога и `if r.invalidator != nil`, который в #93 убран.

---

**Про очередь.** Открыто 20 PR, `main` не двигался с 30 августа. Это уже не вопрос удобства: каждый день ожидания — новый ребейз двадцати веток поверх меняющегося кода, а ребейз у тебя уже терял правки. Проблема сама себя воспроизводит.

Предлагаю выбрать несколько PR, довести их до конца и влить, а остальные перебазировать поверх — вместо того чтобы держать всё в воздухе.
