### PR TITLE
feat: CACHE-04 auto-invalidate product cache after order, remove /cac…

### LINKED ISSUE #32: CACHE-04 · Убрать ручку сброса кеша наружу
### Зачем

Сейчас есть `DELETE /products/{id}/cache` — публичный HTTP-эндпоинт для инвалидации
(`order-service/internal/app/app.go:57`). Это отладочный костыль, торчащий в API:
любой может сбросить кеш чему угодно.

А главное — он не нужен, если инвалидировать там, где данные реально меняются.

### Что сделать

- [x] Инвалидировать кеш товара после списания остатка в #18.
- [x] Убрать эндпоинт `/products/{id}/cache` и метод `InvalidateCache` из сервиса.

### Готово, когда

- [x] После создания заказа `GET /products/{id}` сразу показывает уменьшенный остаток.
- [x] Эндпоинта `/cache` в роутере больше нет.

### На подумать — разобрать на ревью

- Инвалидировать **после** коммита транзакции или внутри? Что произойдёт, если сбросить кеш до коммита, а коммит откатится?
- А если инвалидация упала, а транзакция прошла?

---
**Оценка:** ~2 ч · **Блок 2** · **Зависит от:** #18, #29

### PR DESCRIPTION
**Pull request by xdtqwd**
…he endpoint

### CODE REVIEW

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.**

Суть задачи решена, и **ключевой вопрос решён верно**: `tx.Commit` на строке 70, инвалидация на 75–82 — то есть после коммита. Проверено живьём: заказ на 3 штуки → `stock` сразу 47; заказ на 999 → откат, инвалидации нет, кеш остался корректным. Ручка `DELETE /products/{id}/cache` из роутера убрана, отдаёт 404.

Отдельно отмечу: зависимость введена через узкий локальный интерфейс `Invalidator` на один метод, а не импортом пакета `cache` в репозиторий. Направление мысли правильное.

**Мутационная проверка:** удаление всего блока инвалидации оставляет `go test ./...` зелёным. Поведение не покрыто ничем.

**Галочка «убрать метод `InvalidateCache` из сервиса» стоит, но не выполнена** — роут убран, а `service.InvalidateCache`, `handler.InvalidateProductCache` и интерфейс `Cache` живут дальше.

---

**Про структуру.** Все восемь открытых PR ответвлены от `9243530` — это до мержа #73, который переписал `app.go` в фабрики. Поэтому все восемь конфликтуют, и конфликт везде один и тот же — `app.go`.

Хуже другое: `cached_product_repo.go` живёт в **трёх разных версиях**. В #92 — со счётчиком походов в БД, в #94–97 — с метриками, и эти ветки друг про друга не знают. Смержишь одну, потом другую — либо конфликт, либо, если разрешить невнимательно, чужая правка молча исчезнет.

Перед мержем стоит определиться с порядком и перебазировать, оставив в каждом PR только его дельту.

File: order-service/internal/repository/order.go [hunk 1]
```diff
@@ -71,6 +71,16 @@ func (r *OrderRepo) CreateOrder(ctx context.Context, items []domain.OrderItem) (
 	if err != nil {
 		return 0, err
 	}
+
+	if r.invalidator != nil {
+		for _, item := range items {
+			if err := r.invalidator.InvalidateByID(ctx, item.ProductID); err != nil {
+				_ = err // cache invalidation is best-effort
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order.go]: `_ = err` внутри `if err != nil` — оператор без эффекта. `errcheck` промолчит, а человек прочтёт как «обработано».

Второй вопрос из «На подумать» — «а если инвалидация упала, а транзакция прошла?» — кодом не отвечен: ни лога с order_id, ни метрики, ни стратегии. При недоступном Redis заказ пройдёт, а `GET /products/{id}` до 5 минут будет отдавать старый остаток.

Рядом вторая тонкость: инвалидация идёт с `ctx` HTTP-запроса, а коммит уже прошёл. Отвалится клиент между коммитом и `Delete` — контекст отменён, инвалидации не будет.

**Вопрос:** после коммита время жизни этой операции всё ещё привязано к запросу?

File: order-service/internal/repository/order_repo.go [hunk 2]
```diff
@@ -1,11 +1,19 @@
...
+)
+
+type Invalidator interface {
+	InvalidateByID(ctx context.Context, id int) error
+}
 
 type OrderRepo struct {
-	pool *pgxpool.Pool
+	pool        *pgxpool.Pool
+	invalidator Invalidator
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order_repo.go:16]: `OrderRepo` теперь отвечает за когерентность кеша **чужого** агрегата — товаров.

И заложена мина на будущее: инвалидатором подключён `cachedProductRepo`, то есть **середина** цепочки. Когда ляжет #75, стек станет `L1 → Cached → ProductRepo`, и L1 продолжит десять секунд отдавать старый остаток.

**Вопрос:** какой слой знает и «заказ создан», и «какие товары затронуты»? Сбрасывать надо с вершины стека, а не из его середины.

File: order-service/internal/repository/product_repo.go [hunk 3]
```diff
@@ -9,3 +12,7 @@ type ProductRepo struct {
 func NewProductRepo(pool *pgxpool.Pool) *ProductRepo {
 	return &ProductRepo{pool: pool}
 }
+
+func (r *ProductRepo) InvalidateByID(ctx context.Context, id int) error {
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/product_repo.go]: Возвращает `nil` и ничего не делает — метод добавлен, чтобы удовлетворить компилятор. Базовый репозиторий врёт вызывающему: «инвалидировал».

**Вопрос:** если инвалидация принадлежит только кеширующему слою, что она делает в интерфейсе, который реализует голый Postgres-репозиторий?

File: order-service/internal/repository/cached_product_repo.go [hunk 4]
```diff
@@ -37,26 +38,33 @@ func (r *CachedProductRepo) GetProductByID(ctx context.Context, id int) (*domain
...
+	return val.(*domain.Product), nil
 }
 
 func (r *CachedProductRepo) InvalidateByID(ctx context.Context, id int) error {
 	key := fmt.Sprintf("product:%d", id)
 	if err := r.cache.Delete(ctx, key); err != nil {
 		r.logger.Error("cache delete error", zap.Error(err))
 	}
-	return r.repo.InvalidateByID(ctx, id)
+	return nil
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go]: Вот здесь правка и обесценилась.

Замечание было «ошибка инвалидации теряется». Ты добавил `logger.Error` уровнем выше, в `order.go` — а глотание осталось здесь: ошибка `cache.Delete` логируется и наружу уходит `nil`.

Это единственная реализация `Invalidator`, подключённая в `app.go`. Значит новая ветка `if err != nil { ... }` в `order.go` **никогда не выполнится**.

**Вопрос:** кто в этой цепочке имеет право решить, что ошибка не важна, и как об этом узнает вызывающий?

File: order-service/internal/repository/order.go [hunk 5]
```diff
@@ -71,6 +72,19 @@ func (r *OrderRepo) CreateOrder(ctx context.Context, items []domain.OrderItem) (
 	if err != nil {
 		return 0, err
 	}
+
+	if r.invalidator != nil {
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/order.go]: Инвалидация стала опциональной без предупреждения: забыли передать зависимость — заказы создаются, кеш не сбрасывается, тесты зелёные.

Тот же класс, что «написал и не подключил», только теперь с молчаливым согласием компилятора.

**Вопрос:** нужен ли тут nil-путь вообще? Что было бы, если бы конструктор не принимал `nil`?

File: order-service/internal/repository/l1_product_repo.go [hunk 6]
```diff
@@ -18,12 +18,17 @@ func productKey(id int) string {
 	return fmt.Sprintf("product:%d", id)
 }
 
+type StorageWithInvalidation interface {
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/l1_product_repo.go:21]: Четвёртое описание одной сущности. Сейчас в проекте: `ProductStorage`, `Invalidator`, `StorageWithInvalidation` в `repository` и `service.ProductRepository` — с тем же набором методов.

**Вопрос:** какой из них потребитель, какой поставщик, и сколько можно убрать прямо сейчас?

**Review by kostyavelikiyi — COMMENTED** [review]
**Нельзя мержить.** Понижаю с прошлого «можно, но исправить».

Причина — правка симптома вместо причины, и она обесценила сама себя. Подробности в коде.

**Коммит `fix: log invalidation errors, use context.Background(), ...` не содержит `context.Background()`.** Проверил дифф: там только замена `_ = err` на лог и удаление метода из интерфейса. Замечание про контекст запроса не отработано, но в сообщении заявлено.

**Что исправлено хорошо:** заглушка `ProductRepo.InvalidateByID` убрана вместе с методом из `ProductStorage` — интерфейс перестал требовать от чистого БД-репозитория того, чего он не умеет. Аккуратно.

**Не исправлено:** инвалидатором подключена середина цепочки, а не вершина; `InvalidateCache` в сервисе, хендлере и интерфейсе живёт (галочка «убрать» отмечена); мутация — удаление всего блока инвалидации оставляет тесты зелёными.

**И находка на стыке с #92:** `InvalidateByID` делает `cache.Delete`, но не вызывает `group.Forget(key)`. Лидер singleflight успел прочитать старый остаток, но не дошёл до `Set`; заказ коммитится, `Delete` срабатывает, лидер пишет **устаревшее** значение на 5 минут. Каждый PR по отдельности корректен — ломается стык.

---

### Общее: ребейз теряет правки

За эту итерацию правки пропали **три раза**:

| Где | Что потерялось |
|---|---|
| `main` | подключение L1 к `app.go` — задача #30 закрыта, `NewL1ProductRepo` не вызывается ниоткуда |
| #94, #97 | все вызовы `metrics.*.Inc()` — пакет и `/metrics` есть, счётчики не инкрементятся |
| #94, #97 | роут `DELETE /products/{id}/cache` заменён строкой `/metrics` |

Плюс четыре коммита из пяти в #97 **не собираются** (`not enough arguments in call to repository.NewOrderRepo`) — зелёный только последний. `git bisect` по такой истории невозможен.

**Вопрос, который важнее любого замечания по коду:** как проверить, что ребейз ничего не потерял, кроме как читая диффы глазами? Подсказка — `git range-diff`.

File: order-service/internal/repository/cached_product_repo.go (hunk 4 above)
Comment (xdtqwd) [reply order-service/internal/repository/cached_product_repo.go]: Только вызывающий. CachedProductRepo.InvalidateByID
OrderRepo уже решит что с ней делать

File: order-service/internal/repository/order.go (hunk 5 above)
Comment (xdtqwd) [reply order-service/internal/repository/order.go]: Нет, если invalidator == nil — заказы создаются без инвалидации кэша молча

File: order-service/internal/repository/l1_product_repo.go (hunk 6 above)
Comment (xdtqwd) [reply order-service/internal/repository/l1_product_repo.go:21]: ProductStorage — нужен, это интерфейс у потребителя (CachedProductRepo)
Invalidator — нужен, узкий интерфейс для OrderRepo
StorageWithInvalidation — лишний, создан чтобы обойти проблему
service.ProductRepository — нужен, интерфейс у потребителя (ProductService)

Убрать можно StorageWithInvalidation — он появился как костыль

File: order-service/internal/repository/cached_product_repo.go [hunk 7]
```diff
@@ -37,26 +38,32 @@ func (r *CachedProductRepo) GetProductByID(ctx context.Context, id int) (*domain
...
+	return &cp, nil
 }
 
 func (r *CachedProductRepo) InvalidateByID(ctx context.Context, id int) error {
 	key := fmt.Sprintf("product:%d", id)
-	if err := r.cache.Delete(ctx, key); err != nil {
-		r.logger.Error("cache delete error", zap.Error(err))
-	}
-	return r.repo.InvalidateByID(ctx, id)
+	r.group.Forget(key)
```
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go:67]: `Forget` добавлен правильно, но гонку он закрывает не полностью.

`Forget(key)` снимает ключ с карты, а уже запущенная функция лидера продолжит работу и потом выполнит `cache.Set(..., productTTL)` — то есть запишет только что удалённое значение на пять минут. Порядок `Delete` и `Set` ничем не упорядочен.

**Вопрос:** что именно предотвращает `Forget`, а что нет? И как узнать, что лидер уже отработал?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.**

Это единственный PR из шести, где причину починили **в правильном месте**, а не симптом уровнем выше. Четыре замечания из восьми закрыты: `InvalidateByID` больше не глотает ошибку, `if r.invalidator != nil` убран, `context.Background()` появился, `group.Forget` добавлен. Стык с #92 ты увидел сам — это хорошо.

Осталось: четыре параллельных интерфейса (`ProductStorage`, `Invalidator`, `StorageWithInvalidation`, `service.ProductRepository`); `InvalidateCache` жив в сервисе, хендлере и интерфейсе при отмеченной галочке «убрать»; мутация — удаление блока инвалидации не роняет тесты.

---

**Про стек.** #94 → #95 → #96 → #97: каждый следующий стоит на **доревьюшной** версии предыдущего. Мерж по порядку молча откатит правки — #95 отменит метрики из #94, #96 вернёт дубль `ErrCacheMiss`, который #95 убрал. Плюс все четыре несут старую копию CACHE-04, исправленную в #93.

И общее: `NewL1ProductRepo` не вызывается **ни в одной ветке и в `main`** — L1 мёртв с 30 августа, задача #30 при этом закрыта.

File: order-service/internal/repository/cached_product_repo.go (hunk 7 above)
Comment (kostyavelikiyi) [inline order-service/internal/repository/cached_product_repo.go:67]: `Forget` на месте — гонку он сужает, но не закрывает.

Он снимает ключ с карты, а уже запущенный лидер продолжит работу и потом выполнит `cache.Set(..., productTTL)` — то есть запишет только что удалённое значение на пять минут.

**Вопрос:** что именно предотвращает `Forget`, а что нет? И как узнать, что лидер уже отработал?

**Review by kostyavelikiyi — COMMENTED** [review]
**В целом ок, можно мержить, но надо исправить.** Ветку не трогали с 31 августа, все четыре замечания в силе.

Что сделано верно и осознанно: инвалидация после `tx.Commit`, `context.Background()` вместо контекста запроса, лог с `product_id` и `order_id`. Три решения из четырёх правильные.

Не закрыто:

- Четыре параллельных интерфейса: `ProductStorage`, `StorageWithInvalidation`, `Invalidator`, `service.ProductRepository`.
- `InvalidateCache` жив в сервисе, хендлере и интерфейсе — роут снят, метод остался. Галочка «убрать метод из сервиса» отмечена.
- Мутация: удаление блока инвалидации не роняет тесты.
- **Два коммита из четырёх не собираются** — `dc1c762` и `7836420`.

И расхождение: коммит `139541f` называется «L1 invalidates through full stack», но `app.go` в этой ветке L1 вообще не собирает — `newRepositories` возвращает `cachedProductRepo` напрямую.

---

**Про очередь.** Открыто 20 PR, `main` не двигался с 30 августа. Это уже не вопрос удобства: каждый день ожидания — новый ребейз двадцати веток поверх меняющегося кода, а ребейз у тебя уже терял правки. Проблема сама себя воспроизводит.

Предлагаю выбрать несколько PR, довести их до конца и влить, а остальные перебазировать поверх — вместо того чтобы держать всё в воздухе.

**Comment by kostyavelikiyi** [comment]
Закрываю: суть уехала в main вместе с #97.

Ветка отстала сильно — мерж как есть удалил бы `product-service`, `seed_big.sql`, `coverage_diff.py` и goose-миграции, 2574 удалённые строки. Поэтому взял из неё не коммиты, а решение, и перенёс в #97:

- вызов `InvalidateByID` по всем позициям после создания заказа;
- `group.Forget(key)` в `InvalidateByID`, именно в порядке Delete → Forget;
- инвалидация best-effort: ошибка логируется, но не роняет уже закоммиченный заказ;
- свой `context.Background()` под инвалидацию;
- логгер в `OrderRepo`;
- удаление ручки `/products/{id}/cache` — сброс теперь автоматический.

Отдельно: твой комментарий про порядок Delete → Forget и про оставшееся окно гонки между `Do` и `Set` лидера — верный разбор, я его перенёс в код дословно. Это ровно то рассуждение, которого я ждал от задачи.
